# Generated by Django 5.2.7 on 2025-10-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0004_rename_content_review_text_remove_review_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prj.movie'),
        ),
    ]
