# Generated by Django 5.2.7 on 2025-10-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0005_alter_favorite_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='rating',
        ),
    ]
