# Generated by Django 5.2.7 on 2025-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/'),
        ),
    ]
