# Generated by Django 5.2.7 on 2025-10-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0008_profile_avatar_profile_bio_profile_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='text',
        ),
    ]
