# Generated by Django 5.2.7 on 2025-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0010_category_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(related_name='movies', to='prj.category'),
        ),
    ]
